name: ets
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  archive: ^3.3.1
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.1
  flutter_ble_lib_ios_15: ^2.5.2
  flutter_native_splash: ^2.1.6
  flutter_spinbox: ^0.9.0
  get: ^4.6.5
  location: ^4.4.0
  path_provider: ^2.0.11
  share_plus: ^4.0.10+1
  flutter_blue_plus: 1.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

